#!/bin/sh
# live-build: параметры дистрибутива ShidikusikOS.
# Вызывается автоматически командой `lb config` из каталога iso/.
set -e

lb config noauto \
    --distribution trixie \
    --architecture amd64 \
    --archive-areas "main contrib non-free-firmware" \
    --binary-images iso-hybrid \
    --debian-installer none \
    --linux-flavours amd64 \
    --apt-recommends false \
    --iso-application "ShidikusikOS" \
    --iso-publisher "ShidikusikOS project" \
    --iso-volume "ShidikusikOS" \
    --bootappend-live "boot=live components quiet splash username=shidik hostname=shidikusik" \
    "${@}"
